### ISSUE TITLE
这个功能有没有考虑直接合并到 uni-use 中，让 uni-use 更健壮

### ISSUE THREAD

**Issue by Megasu** [uni-helper/uni-env#2]
### 对问题的清晰和简明的描述

如题

### 推荐的解决方案

```
import { isMpWeixin } from '@uni-helper/uni-use'
```

代替

```
import { isMpWeixin } from "@uni-helper/uni-env";
```

### 替代方案

如题

### 额外上下文

无

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
`@uni-helper/uni-use` 定位是有状态逻辑方法的集合， `@uni-helper/uni-env` 是通过环境变量判断环境的，不太符合前者定位。

**Comment by ModyQyW** [comment]
如果还有问题欢迎提出！暂时先关闭了。🙏
