### ISSUE TITLE
isMpWeixin bug

### ISSUE THREAD

**Issue by flowerwOw0316** [uni-helper/uni-env#20]
### Describe the bug

小程序打印为false

### Reproduction

直接打印

### System Info

小程序

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute) and [Notes from a tired maintainer](https://github.com/pi0/tired-maintainer).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by ModyQyW** [comment]
疑似std-env的问题，可能需要去掉std-env依赖
