### ISSUE TITLE
0.1.5 小程序 process is not defined

### ISSUE THREAD

**Issue by flowerwOw0316** [uni-helper/uni-env#21]
### 描述问题

![image](https://github.com/user-attachments/assets/d71c5e12-18af-4e0e-b4fd-bcf2cc2d65b9)
![image](https://github.com/user-attachments/assets/f0bc53e7-491e-406c-96cb-b9ee4c9edb8d)
升级0.1.5后出现process is not defined

### 复现

打开小程序开发者工具就报错

### 系统信息

"@uni-helper/uni-env": "^0.1.5"

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by ModyQyW** [comment]
std-env 只能读取到直接设置的环境变量，对于替换类的无能为力（这正是 uni-app 的行为，参考 https://github.com/dcloudio/uni-app/blob/v3.0.0-4020920240930001/packages/uni-cli-shared/src/env/define.ts），所以前面会出现 std-env 读取到 undefined 的情况。

uni-env 又是根据 https://github.com/dcloudio/uni-app/blob/v3.0.0-4020920240930001/packages/shims-node.d.ts 来确定环境变量的，与 https://github.com/dcloudio/uni-app/blob/v3.0.0-4020920240930001/packages/uni-cli-shared/src/env/define.ts 有出入。如果说 uni-app 官方不补全这一些环境变量，那只能提供用户侧的 vite 插件来补全这一部分内容，否则可能要废弃掉 uni-env。

目前可以先考虑直接用 process.env.UNI_PLATFORM === 'mp-weixin' 来判断是否微信环境，后续确认怎么处理，非常抱歉

**Comment by ModyQyW** [comment]
补充rollup行为 https://github.com/rollup/rollup/issues/2569

**Comment by KeJunMao** [comment]
如 README 中所示，我创建这个包的初衷 ”更多的是为插件开发者提供“

我觉得可以改下文档，并在代码层判断下，如果是运行时引入了直接抛异常。

运行时引入出错是正常的~

**Comment by KeJunMao** [comment]
而且我看到最新的实现删了std-env，只面向打包阶段都不需要删，环境是没有问题的！

**Comment by ModyQyW** [comment]
是呢，要加回来

**Comment by ModyQyW** [comment]
v0.1.7
