### ISSUE TITLE
补充更多 platform

### ISSUE THREAD

**Issue by ModyQyW** [uni-helper/uni-env#3]
### 对问题的清晰和简明的描述

目前 platform 和官网有些出入。

https://github.com/uni-helper/uni-env/blob/main/src/index.ts#L5-L17

<img width="337" alt="image" src="https://github.com/uni-helper/uni-env/assets/31850793/c14a35f9-0bdc-4709-80f1-a720b9677ab5">

https://uniapp.dcloud.net.cn/quickstart-cli.html#%E8%BF%90%E8%A1%8C%E3%80%81%E5%8F%91%E5%B8%83uni-app

<img width="1157" alt="image" src="https://github.com/uni-helper/uni-env/assets/31850793/113d58c4-2c6b-46e3-8b44-032fd3cccd76">

### 推荐的解决方案

- app -> app-plus ？我不太确定二者的区别
- 补充 mp-360
- 补充 mp-jd
- 补充 mp-xhs

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
这个是从 uniapp 的 vite 插件里抄过来的，platform 自定义的话理论上应该还要支持 string?

**Comment by ModyQyW** [comment]
>  这个是从 uniapp 的 vite 插件里抄过来的

那我感觉还是别加了吧……

> platform 自定义的话理论上应该还要支持 string?

如果增加 string，ts 应该会全推导成 string……我觉得可以考虑下自定义的时候用户如何自己扩展类型？ 🤔️

**Comment by KeJunMao** [comment]
扩展类型可以的！
